spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/wallet
    username: klay
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    separator: //
